// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package database

import (
	"context"
)

const addItemHistory = `-- name: AddItemHistory :exec
INSERT INTO ge_price_history (
        item_id,
        price_timestamp,
        avg_high_price,
        avg_low_price,
        high_volume,
        low_volume
    )
VALUES ($1, $2, $3, $4, $5, $6)
`

type AddItemHistoryParams struct {
	ItemID         int32
	PriceTimestamp int64
	AvgHighPrice   int32
	AvgLowPrice    int32
	HighVolume     int64
	LowVolume      int64
}

func (q *Queries) AddItemHistory(ctx context.Context, arg AddItemHistoryParams) error {
	_, err := q.db.ExecContext(ctx, addItemHistory,
		arg.ItemID,
		arg.PriceTimestamp,
		arg.AvgHighPrice,
		arg.AvgLowPrice,
		arg.HighVolume,
		arg.LowVolume,
	)
	return err
}

const getItemHistory = `-- name: GetItemHistory :many
SELECT id, item_id, price_timestamp, avg_high_price, avg_low_price, high_volume, low_volume, created_at
FROM ge_price_history
WHERE item_id = $1
`

func (q *Queries) GetItemHistory(ctx context.Context, itemID int32) ([]GePriceHistory, error) {
	rows, err := q.db.QueryContext(ctx, getItemHistory, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GePriceHistory
	for rows.Next() {
		var i GePriceHistory
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.PriceTimestamp,
			&i.AvgHighPrice,
			&i.AvgLowPrice,
			&i.HighVolume,
			&i.LowVolume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
