// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type GePriceHistory struct {
	ID             int64
	ItemID         int32
	PriceTimestamp int64
	AvgHighPrice   int32
	AvgLowPrice    int32
	HighVolume     int64
	LowVolume      int64
	CreatedAt      time.Time
}
