// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type GePriceHistory struct {
	ID             int64     `json:"id"`
	ItemID         int32     `json:"itemId"`
	PriceTimestamp int64     `json:"priceTimestamp"`
	AvgHighPrice   int32     `json:"avgHighPrice"`
	AvgLowPrice    int32     `json:"avgLowPrice"`
	HighVolume     int64     `json:"highVolume"`
	LowVolume      int64     `json:"lowVolume"`
	CreatedAt      time.Time `json:"createdAt"`
}
